#!/bin/bash
VLAN_ADDR=192.168.90.2
PXECID=$(docker ps --no-trunc | grep 'pxe_coreos:latest' | awk '{print $1}')
case "$1" in
        '')
                echo "I need one parameter: start | stop | status | enter | logs"
        ;;
	start)
                if [ -z "$PXECID" ]; then
                        echo it looks like there is already a pxe container running...
                	exit 1
		fi
		PXECID=$(docker run -v /home/core/pxe_coreos.data:/cloudconfigserver/data -d pxe_coreos)
		if [ -z "$PXECID" ]; then
   			echo something bad happened, container not launched.
   			exit 1
		fi
		sudo /root/bin/pipework br-internal $PXECID $VLAN_ADDR/24
	;;
        enter)
                if [ -z "$PXECID" ]; then
                        echo could not find pxe container.
                exit 1
                fi
                docker exec -i -t $PXECID bash
        ;;
	status)
		docker ps -a | grep -e 'CONTAINER\|pxe_coreos'
	;;
	*)
		if [ -z "$PXECID" ]; then
   			echo could not find pxe container.
   		exit 1
		fi
		docker $1 $PXECID
	;;
esac